from enum import Enum

class AsyncTaskStatus(str, Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"

class AsyncTaskResultType(str, Enum):
    ARCHIVE = "ARCHIVE"
    RAW_RESULT = "RAW_RESULT"
    TEMPORARY_URL_ACCESS = "TEMPORARY_URL_ACCESS"

class AsyncTaskType(str, Enum):
    EXPORT_INVENTORY_RESPONSIBILITY_AGREEMENT_REPORT = "EXPORT_INVENTORY_RESPONSIBILITY_AGREEMENT_REPORT"
    EXPORT_ANALYTICALT_REPORT = "EXPORT_ANALYTICALT_REPORT"
    EXPORT_ITEMS_IMAGES = "EXPORT_ITEMS_IMAGES"
    UPLOAD_ITEMS_IMAGES = "UPLOAD_ITEMS_IMAGES"